### ISSUE TITLE
Support editing a previous answer without refilling the entire form

### ISSUE THREAD

**Issue by sequoia-tree** [BerkeleyAutomation/malasakit-v1#31] opened 2017-05-25 19:01 UTC
Users want to change answer in one of the questions (upon seeing it in the review page), presses back until desired question number, then answers, but is frustrated that he/she has to answer all of the other questions again

**Comment by sequoia-tree** [comment] 2017-05-25 19:04
Also backspace (or the keyboard shortcut for "back") causes issues in Safari, Chrome, presumably others.

**Comment by sequoia-tree** [comment] 2017-05-25 19:52
Users want to change answer in one of the questions (upon seeing it in the review page), presses back until desired question number, then answers, but is frustrated that he/she has to answer all of the other questions again

**Comment by jonathan-j-lee** [comment] 2017-05-29 19:46
This issue is a combination of three separate issues, two of which are duplicates of #21 and #29. I've edited this issue so that it only covers the answer editing issue.

**Comment by jonathan-j-lee** [comment] 2017-06-09 21:10
Duplicate of #55, which is better formulated than this issue.

**Closed by jonathan-j-lee** 2017-06-09 21:10 UTC
Labels: bug, duplicate
